# Generated by Django 4.2.2 on 2023-07-06 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='disclosure',
            field=models.TextField(blank=True, null=True, verbose_name='disclosure'),
        ),
    ]
