# Generated by Django 4.2.2 on 2023-07-10 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='urladdress',
            name='url',
            field=models.CharField(max_length=255),
        ),
    ]
